#!/bin/sh

/etc/rc.d/init.d/autoexec stop > /dev/null 2>&1

/usr/libexec/sftp-server.bin

dos2unix /local/etc/sysconfig/*.csv > /dev/null 2>&1
dos2unix /local/etc/sysconfig/*.conf > /dev/null 2>&1
dos2unix /local/data/custom*/*.csv > /dev/null 2>&1

/etc/rc.d/init.d/autoexec start > /dev/null 2>&1

exit 0
