#!/bin/sh

UPDDIR=/update

/usr/libexec/sftp-server.bin


# Do not restart anything unless instructed oterhwise.
restart_HMI=false
restart_PLC=false

if test -f ${UPDDIR}/Alarms.csv; then
	restart_HMI=true
	restart_PLC=true

	/etc/rc.d/init.d/autoexec stop_hmi > /dev/null 2>&1
	/etc/rc.d/init.d/autoexec stop_plc > /dev/null 2>&1

	mv ${UPDDIR}/Alarms.csv /local/etc/sysconfig
fi

if test -f ${UPDDIR}/system.ini; then
	restart_HMI=true
	restart_PLC=true

	/etc/rc.d/init.d/autoexec stop_hmi > /dev/null 2>&1
	/etc/rc.d/init.d/autoexec stop_plc > /dev/null 2>&1

	mv ${UPDDIR}/system.ini /local/etc/sysconfig
fi

if test -f ${UPDDIR}/application.conf; then
	restart_PLC=true

	/etc/rc.d/init.d/autoexec stop_plc > /dev/null 2>&1

	mv ${UPDDIR}/application.conf /local/etc/sysconfig
fi

if test -f ${UPDDIR}/atn01.conf; then
	restart_HMI=true

	/etc/rc.d/init.d/autoexec stop_hmi > /dev/null 2>&1

	mv ${UPDDIR}/atn01.conf /local/etc/sysconfig
fi

if test -f ${UPDDIR}/Commpar.csv; then
	restart_PLC=true

	/etc/rc.d/init.d/autoexec stop_plc > /dev/null 2>&1

	mv ${UPDDIR}/Commpar.csv /local/etc/sysconfig
fi

if test -f ${UPDDIR}/Crosstable.csv; then
	restart_HMI=true
	restart_PLC=true

	/etc/rc.d/init.d/autoexec stop_hmi > /dev/null 2>&1
	/etc/rc.d/init.d/autoexec stop_plc > /dev/null 2>&1

	mv ${UPDDIR}/Crosstable.csv /local/etc/sysconfig
fi

if test -f ${UPDDIR}/hmi; then
	restart_HMI=true

	/etc/rc.d/init.d/autoexec stop_hmi > /dev/null 2>&1

	mv ${UPDDIR}/Alarms.csv /local/root
fi

if test -f ${UPDDIR}/splash.png; then
	mv ${UPDDIR}/splash.png /local/etc/sysconfig
fi

if test -f ${UPDDIR}/store1.csv; then
	mv ${UPDDIR}/store1.csv /local/data/customstore
fi

if test -f ${UPDDIR}/trend1.csv; then
	mv ${UPDDIR}/trend1.csv /local/data/customtrend
fi

if test -f ${UPDDIR}/systool.png ; then
	mv ${UPDDIR}/systool.png /local/etc/sysconfig
fi


eval "$restart_PLC" && /etc/rc.d/init.d/autoexec start_plc > /dev/null 2>&1
eval "$restart_HMI" && /etc/rc.d/init.d/autoexec start_hmi > /dev/null 2>&1

exit 0

###  File                            HMI        PLC        Destinazione             Note
###  -----------------------------------------------------------------------------------
###  Alarms.csv                      riavviare  riavviare  /local/etc/sysconfig
###  application.conf -> system.ini  niente     riavviare  /local/etc/sysconfig     *
###  atn01.conf -> system.ini        riavviare  niente     /local/etc/sysconfig     *
###  Commpar.csv -> system.ini       niente     riavviare  /local/etc/sysconfig     *
###  Crosstable.csv                  riavviare  riavviare  /local/etc/sysconfig
###  hmi                             riavviare  niente     /local/root
###  splash.png                      niente     niente     /local/etc/sysconfig
###  store1.csv                      niente     niente     /local/data/customstore
###  trend1.csv                      niente     niente     /local/data/customtrend
###  systool.png                     niente     niente     /local/etc/sysconfig     **
### 
### Note
### ----
### *  quando ci sarà il nuovo system.ini, bisognerà riavviare sia HMI che PLC
### ** non più utilizzato (è usato solo da systool che abbiamo deciso di non mettere)
