#!/bin/sh

test -z "$ACTION" && exit 0

if test "$DEVTYPE" = "usb_device"; then
    test -z "$DEVPATH" && exit 0

    if test "$ACTION" = "add"; then
        ms_vendor="$(cat /sys${DEVPATH}/idVendor)"
        ms_product="$(cat /sys${DEVPATH}/idProduct)"
        test \( -z "$ms_vendor" \) -o \( -z "$ms_product" \) && exit 1

        ms_data="$(tar Oxjf /usr/share/usb_modeswitch/configPack.tar.bz2 ${ms_vendor}:${ms_product} 2>/dev/null)"
        if test -n "$ms_data"; then
            usb_modeswitch -v $ms_vendor -p $ms_product -f "$ms_data"
###         else
###             optconf=/sys/bus/usb-serial/drivers/option1/new_id
### 
###             modprobe option
###             test -f $optconf && echo "$ms_vendor $ms_product" > $optconf
        fi
    elif test "$ACTION" = "remove"; then
        modprobe -r option
    else
        exit 0
    fi
elif test -n "$MDEV" -a "$MDEV" = "ttyUSB2"; then
    test "$SUBSYSTEM" = "usb-serial" || exit 0

    if test "$ACTION" = "add"; then
        /bin/rm -f ppp
        /bin/mknod ppp c 108 0

        /usr/sbin/usb3g.sh start
    elif test "$ACTION" = "remove"; then
        /bin/rm -f ppp

        /usr/sbin/usb3g.sh stop
    else
        exit 0
    fi
else
    exit 0
fi
