Summary: Perl bindings to the rpmlib API
Name: Perl-RPM
Version: 0.32
Release: 1
Epoch: 1
Vendor: Randy J. Ray
Copyright: Artistic
Group: Applications/CPAN
Source: Perl-RPM-0.32.tar.gz
Url: http://www.blackperl.com/Perl-RPM
BuildRequires: perl >= 0:5.00503
Requires: perl >= 0:5.00503
Provides: Perl-RPM = 0.32
BuildRoot: %{_tmppath}/%{name}-root

%description
Native Bindings to the RPM API for Perl 5.005 and later. Uses a combination
of Perl and C/XS (compiled) code to provide access to the RPM database,
headers of installed packages, and more.

%prep
%setup -q -n Perl-RPM-%{version} 

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL

%clean 
rm -rf $RPM_BUILD_ROOT

%install
rm -rf $RPM_BUILD_ROOT
install_dir=/usr/lib/perl5/site_perl/5.6.0/i386-linux
mkdir -p $RPM_BUILD_ROOT/$installdir
make PREFIX=$RPM_BUILD_ROOT/usr install

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print |
        sed "s@^$RPM_BUILD_ROOT@@g" |
        grep -v perllocal.pod |
        grep -v "\.packlist" > Perl-RPM-0.32-filelist
if [ "$(cat Perl-RPM-0.32-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit -1
fi

%files -f Perl-RPM-0.32-filelist
%defattr(-,root,root)

%changelog
* Tue Oct 10 2000 Randy J. Ray <rjray@blackperl.com>
- Turned into a meta-file that gets filled in by MakeMaker

* Tue Oct  3 2000 Jeff Johnson <jbj@redhat.com>
- update to 0.28.

* Mon Oct  2 2000 root <root@redhat.com>
- Spec file was autogenerated.
